apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: next16-ingress
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod-new"
    traefik.ingress.kubernetes.io/router.tls: "true"
    traefik.ingress.kubernetes.io/router.entrypoints: "web,websecure"
    traefik.ingress.kubernetes.io/router.middlewares: ""
spec:
  ingressClassName: traefik
  tls:
    - hosts:
        - next16.catshoulder.dev
      secretName: next16-tls-v2
  rules:
    - host: next16.catshoulder.dev
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: next16-service
                port:
                  number: 8080
